ubiqube/quickstart

README.adoc

"docker-compose up -d  --build" should do all the work, building and
pulling the images.
To use docker-compose pull all images need to be in the dockerhub
repository

Remove step 7

---

README.adoc

Remove quiet pull option. If keep, a minimum version of docker compose is needed

Update README.adoc - Remove quiet pull

---

docker-compose.yml

Update the UI image to include a fix for Airbus
http://agile.ubiqube.com/browse/MSA-8311

Update UI docker image tag

---

docker-compose.yml

Linux-ME: set device mapping and cap

---

scripts/upgrade.sh

add processing of curl response when getting the version and API are down

Upgrade script

---

lab/msa_dev/resources/scripts/install_libraries.sh

install libraries with option for a local dev branch, auto-merge, license installation

local git repo management

---

docker-compose.simple.ha.yml
docker-compose.yml
lab/msa_dev/resources/scripts/create_mini_lab.sh

add missing param hostname
update msadev image tag

Fix minilab script

---

docker-compose.simple.ha.yml
docker-compose.yml
lab/linux.me/Dockerfile
lab/linux.me/snmpd.conf
lab/linux.me/start.sh
lab/msa_dev/resources/scripts/create_mini_lab.sh

update linux me image to support centos 7

[MARK-222] update linux me image to support centos 7

---

docker-compose.simple.ha.yml
docker-compose.yml
scripts/install.sh

Merge 2.4.0 RC1 to 2.4.0 GA quickstart

Merge 2.4.0 RC1 to 2.4.0 GA quickstart

---

scripts/install.sh

Revert "MSA-10043 - script path adjustment"

---

scripts/install.sh

Get Back "MSA-10043 - script path adjustment""

---

docker-compose.yml
scripts/install.sh
scripts/install_win.sh

Merge 2.5.1 in master

---

docker-compose.simple.ha.yml

Update docker-compose.simple.ha.yml - 2.5.1 for HA

---

docker-compose.simple.ha.yml
docker-compose.yml
scripts/install.sh
scripts/install_win.sh

Update master with 2.5.2 images (standalone + HA) and upgrade scripts

2.5.2 updates

---

scripts/install.sh
scripts/install_win.sh

- Style: replace tab -> spaces
- MSA-10578 - Detect when upgrade fails.

MSA 10578 detect upgrade when failed

---

scripts/install.sh
scripts/swarm-fix-all-nodes.sh

- Fix swarm routers for Syslogs
- Fix swarm routes for all the nodes

MSA 9893 fix swarm route

---

docker-compose.es_cluster.yml
docker-compose.ha.yml
docker-compose.light.yml
docker-compose.yml
stack.es_cluster.yml

* Update docker-compose.yml
Update front, api + ui tags (from build 108 to 110)
* Update docker-compose.light.yml
* Update stack.es_cluster.yml
update tags
* Update docker-compose.ha.yml
* Update docker-compose.es_cluster.yml

update with latest from master

---

docker-compose.es_cluster.yml
docker-compose.ha.yml
docker-compose.light.yml
docker-compose.yml
stack.es_cluster.yml

* Update docker-compose.yml
Update front, api + ui tags (from build 108 to 110)
* Update docker-compose.light.yml
* Update stack.es_cluster.yml
update tags
* Update docker-compose.ha.yml
* Update docker-compose.es_cluster.yml

2.8.2 (#161)

---

scripts/install.sh

When the option is present, the script should be called every time, but
only on HA mode

Script should run every time

---

docker-compose.ha.yml

* rsyslog ports in mode host in docker-compose.ha.yml
* add some comment for rsyslog port
---------

rsyslog ports in mode host in docker-compose.ha.yml (#216)
